[package]
name = "libsql_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "libsql_native"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
libsql = "0.6.0"
tokio = { version = "1.43.0", features = ["sync"] }
once_cell = "1.20.2"
